/* eslint-disable no-unused-vars */
export const ASSOCIATION_DETAILS_REQUEST = 'ASSOCIATION_DETAILS_REQUEST';
export const ASSOCIATION_DETAILS_SUCCESS = 'ASSOCIATION_DETAILS_SUCCESS';
export const ASSOCIATION_DETAILS_FAIL = 'ASSOCIATION_DETAILS_FAIL';
