/* eslint-disable no-unused-vars */
export const ASSOCIATION_DETAILS_REQUEST = 'ASSOCIATION_DETAILS_REQUEST';
export const ASSOCIATION_DETAILS_SUCCESS = 'ASSOCIATION_DETAILS_SUCCESS';
export const ASSOCIATION_DETAILS_FAIL = 'ASSOCIATION_DETAILS_FAIL';
export const ASSOCIATION_DETAILS_RESET = 'ASSOCIATION_DETAILS_RESET';

export const ASSOCIATION_BY_ID_REQUEST = 'ASSOCIATION_BY_ID_REQUEST';
export const ASSOCIATION_BY_ID_SUCCESS = 'ASSOCIATION_BY_ID_SUCCESS';
export const ASSOCIATION_BY_ID_FAIL = 'ASSOCIATION_BY_ID_FAIL';
export const ASSOCIATION_BY_ID_RESET = 'ASSOCIATION_BY_ID_RESET';

export const ASSOCIATIONS_LIST_REQUEST = 'ASSOCIATIONS_LIST_REQUEST';
export const ASSOCIATIONS_LIST_SUCCESS = 'ASSOCIATIONS_LIST_SUCCESS';
export const ASSOCIATIONS_LIST_FAIL = 'ASSOCIATIONS_LIST_FAIL';
export const ASSOCIATIONS_LIST_RESET = 'ASSOCIATIONS_LIST_RESET';

export const ASSOCIATION_UPDATE_REQUEST = 'ASSOCIATION_UPDATE_REQUEST';
export const ASSOCIATION_UPDATE_SUCCESS = 'ASSOCIATION_UPDATE_SUCCESS';
export const ASSOCIATION_UPDATE_FAIL = 'ASSOCIATION_UPDATE_FAIL';
export const ASSOCIATION_UPDATE_RESET = 'ASSOCIATION_UPDATE_RESET';

export const ASSOCIATION_DELETE_REQUEST = 'ASSOCIATION_DELETE_REQUEST';
export const ASSOCIATION_DELETE_SUCCESS = 'ASSOCIATION_DELETE_SUCCESS';
export const ASSOCIATION_DELETE_FAIL = 'ASSOCIATION_DELETE_FAIL';
export const ASSOCIATION_DELETE_RESET = 'ASSOCIATION_DELETE_RESET';

export const ASSOCIATION_REGISTER_REQUEST = 'ASSOCIATION_REGISTER_REQUEST';
export const ASSOCIATION_REGISTER_SUCCESS = 'ASSOCIATION_REGISTER_SUCCESS';
export const ASSOCIATION_REGISTER_FAIL = 'ASSOCIATION_REGISTER_FAIL';
export const ASSOCIATION_REGISTER_RESET = 'ASSOCIATION_REGISTER_RESET';