/* eslint-disable no-unused-vars */
export const ASSOCIATION_DETAILS_REQUEST = 'ASSOCIATION_DETAILS_REQUEST';
export const ASSOCIATION_DETAILS_SUCCESS = 'ASSOCIATION_DETAILS_SUCCESS';
export const ASSOCIATION_DETAILS_FAIL = 'ASSOCIATION_DETAILS_FAIL';
export const ASSOCIATION_DETAILS_RESET = 'ASSOCIATION_DETAILS_RESET';

export const ASSOCIATIONS_LIST_REQUEST = 'ASSOCIATIONS_LIST_REQUEST';
export const ASSOCIATIONS_LIST_SUCCESS = 'ASSOCIATIONS_LIST_SUCCESS';
export const ASSOCIATIONS_LIST_FAIL = 'ASSOCIATIONS_LIST_FAIL';
export const ASSOCIATIONS_LIST_RESET = 'ASSOCIATIONS_LIST_RESET';
