/* eslint-disable no-unused-vars */
export const WATER_CONSUMPTION_REQUEST = 'WATER_CONSUMPTION_REQUEST';
export const WATER_CONSUMPTION_SUCCESS = 'WATER_CONSUMPTION_SUCCESS';
export const WATER_CONSUMPTION_FAIL = 'WATER_CONSUMPTION_FAIL';
