/* eslint-disable no-unused-vars */
export const WATER_CONSUMPTION_REQUEST = 'WATER_CONSUMPTION_REQUEST';
export const WATER_CONSUMPTION_SUCCESS = 'WATER_CONSUMPTION_SUCCESS';
export const WATER_CONSUMPTION_FAIL = 'WATER_CONSUMPTION_FAIL';
export const WATER_CONSUMPTION_RESET = 'WATER_CONSUMPTION_RESET';

export const WATER_CONSUMPTION_UPDATE_REQUEST = 'WATER_CONSUMPTION_UPDATE_REQUEST';
export const WATER_CONSUMPTION_UPDATE_SUCCESS = 'WATER_CONSUMPTION_UPDATE_SUCCESS';
export const WATER_CONSUMPTION_UPDATE_FAIL = 'WATER_CONSUMPTION_UPDATE_FAIL';
export const WATER_CONSUMPTION_UPDATE_RESET = 'WATER_CONSUMPTION_UPDATE_RESET';

export const WATER_CONSUMPTION_LIST_REQUEST = 'WATER_CONSUMPTION_LIST_REQUEST';
export const WATER_CONSUMPTION_LIST_SUCCESS = 'WATER_CONSUMPTION_LIST_SUCCESS';
export const WATER_CONSUMPTION_LIST_FAIL = 'WATER_CONSUMPTION_LIST_FAIL';
export const WATER_CONSUMPTION_LIST_RESET = 'WATER_CONSUMPTION_LIST_RESET';

export const WATER_CONSUMPTION_MONTH_REQUEST = 'WATER_CONSUMPTION_MONTH_REQUEST';
export const WATER_CONSUMPTION_MONTH_SUCCESS = 'WATER_CONSUMPTION_MONTH_SUCCESS';
export const WATER_CONSUMPTION_MONTH_FAIL = 'WATER_CONSUMPTION_MONTH_FAIL';
export const WATER_CONSUMPTION_MONTH_RESET = 'WATER_CONSUMPTION_MONTH_RESET';